# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='notes',
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='facebook',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
